apiVersion: v1
kind: Pod
metadata:
  name: elastalert-tools
  labels:
    app: elastalert-tools
spec:
  containers:
  - image: elastalert
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: elastalert-tools
  restartPolicy: Always